#nameOverride: "my-example"
fullnameOverride: "myfullname"

annotations:
  common/first: "true"
  common/second: "true"

gcpProject: "my-google-project"
providerConfigRef: gcp-my-google-project

GlobalAddress:
  externalAddress:
    description: Just an example
    address: 127.0.0.1
    addressType: EXTERNAL

ManagedSSLCertificate:
  my-external-name:
    domains:
    - test.example.com.

ComputeAddress:
  externalAddress:
    description: Just an example
    address: 127.0.0.1
    addressType: EXTERNAL
    region: us-west1

projects:
  appventure-id:
    appventure-id-creds:
      ProviderConfig:
        name: pepito
        key: private_key

  kubertonic:
    crossplane-bucket-creds:
      ProviderConfig:
        name: crossplane--bucket-prod
        key: private_key

    crossplane-core-385109-id-creds:
      ProviderConfig:
        name: pepito
        key: private_key
      ServiceAccounts:
        name1:
          deletionPolicy: Delete
          description: "My Service Account 1 Description!"
        name2:
          deletionPolicy: Rebuena
          description: "My Service Account 2 Description!"
  kubertonic-blue:
    kubertonics-blue-creds:
      ProviderConfig:
        name: pepito
        key: private_key
      ServiceAccounts:
        name3:
          deletionPolicy: Delete
          description: "My Service Account 3 Description!"
        name4:
          deletionPolicy: Rebuena
          description: "My Service Account 4 Description!"
      ServiceAccountKeys:
        name1:
          deletionPolicy: Delete
        name2:
          deletionPolicy: Rebuena
          useServiceAccountId: true
      ProjectIAMMembers:
        name1:
          annotations:
            specific: "true"
          deletionPolicy: Delete
          role: "roles/secretmanager.secretAccessor"
        name2:
          deletionPolicy: Rebuena
          customRole: "database_admin"
          type: group
          email: core@softonic.com

      ProjectIAMCustomRoles:
        database-admin:
          externalName: database_admin
          title: Database Admin
          description: Custom role for administrate databases
          providerConfigRef: provider-ref
          permissions:
          - cloudsql.databases.create
          - cloudsql.databases.delete
          - cloudsql.databases.update
          - cloudsql.instances.create
          - cloudsql.instances.delete
          - cloudsql.instances.update
          - cloudsql.users.create
          - cloudsql.users.delete
          - cloudsql.users.update


DatabaseInstances:
  db-name:
    externalName: my-db-external-name
    databaseVersion: POSTGRES_14
    deletionProtection: true
    region: europe-west1
    connectionSecret:
      name: my-db-connection
      namespace: ""
    settings:
      - tier: db-f1-micro
        #diskSize: 20
        diskType: PD_SSD
        diskAutoresize: true
        activationPolicy: ALWAYS
        availabilityType: ZONAL
        #deletionProtectionEnabled: true
        databaseFlags: []
        insightsConfig:
          - queryInsightsEnabled: false
        locationPreference:
          - zone: europe-west1-b
        ipConfiguration:
          - privateNetwork: projects/project-name/global/networks/network-name
            ipv4Enabled: false
        maintenanceWindow:
          - updateTrack: stable
            day: 2
            hour: 11
        backupConfiguration:
          - enabled: true
            location: eu
            pointInTimeRecoveryEnabled: true
            transactionLogRetentionDays: 7
            backupRetentionSettings:
              - retainedBackups: 7
        userLabels:
          site: global
          service: my-service

DatabaseUsers:
  postgres:
    databaseInstance: db-name
    passwordSecretRef:
      key: postgres-password
      name: postgresql
      namespace: my-namespace
  mysql:
    databaseInstance: db-name-mysql
    host: "%"
    userSecret:
      name: my-db-user
      namespace: my-namespace

CertificateMaps:
  softonic-ru:
    externalName: softonic-ru
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    labels:
      softonic.io/certificateMap: softonic-ru
CertificateMapEntries:
  softonic-ru:
    externalName: softonic-ru
    hostname: "softonic.ru"
    deletionPolicy: Orphan
    description: "certificate map entry for softonic.ru"
    certificate: "softonic-ru"
    matchLabels:
      softonic.io/certificateMap: softonic-ru
  wildcard-softonic-ru:
    externalName: wildcard-softonic-ru
    hostname: "*.softonic.ru"
    deletionPolicy: Orphan
    description: "certificate map entry wildcard for softonic.ru"
    certificate: "softonic-ru"
    matchLabels:
      softonic.io/certificateMap: softonic-ru
Certificates:
  softonic-ru:
    externalName: softonic-ru
    gcpProjectId: "956089745671"
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    domains:
    - '*.softonic.ru'
    - 'softonic.ru'
    scope: "DEFAULT"
    dnsAuthorization: 'softonic-ru'
dnsAuthorizations:
  softonic-ru:
    externalName: softonic-ru
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    domain: softonic.ru
  softonic-pl:
    externalName: softonic-pl
    deletionPolicy: Orphan
    description: "certificate manager for softonic.pl"
    domain: softonic.pl
dnsMappings:
  - authorization: "softonic-ru"
    domains:
      - "softonic.ru"
  - authorization: "softonic-pl"
    domains:
      - "softonic.pl"
      - "*.softonic.pl"
Buckets:
  sft-grafana-prod:
    providerConfigRef: crossplane-bucket-creds
    externalName: sft-grafana-prod
    location: EUROPE-WEST1
    storageClass: REGIONAL
BucketIAMMembers:
  grafana:
    providerConfigRef: crossplane-bucket-creds
    bucket: "sft-grafana-prod"
    member: "serviceAccount:test@kubertonic.iam.gserviceaccount.com"
    role: "projects/kubertonic/roles/softonic_storage_admin"
