#nameOverride: "my-example"
fullnameOverride: "myfullname"

gcpProject: my-google-project
providerConfigRef: gcp-my-google-project

ServiceAccounts:
  name1:
    deletionPolicy: Delete
    description: "My Service Account 1 Description!"
  name2:
    deletionPolicy: Rebuena
    description: "My Service Account 2 Description!"

ServiceAccountKeys:
  name1:
    deletionPolicy: Delete
  name2:
    deletionPolicy: Rebuena

ProjectIAMCustomRoles:
  database-admin:
    project: ""
    externalName: database_admin
    title: Database Admin
    description: Custom role for administrate databases
    providerConfigRef: provider-ref
    permissions:
    - cloudsql.databases.create
    - cloudsql.databases.delete
    - cloudsql.databases.update
    - cloudsql.instances.create
    - cloudsql.instances.delete
    - cloudsql.instances.update
    - cloudsql.users.create
    - cloudsql.users.delete
    - cloudsql.users.update

ProjectIAMMembers:
  name1:
    deletionPolicy: Delete
    role: "roles/secretmanager.secretAccessor"
  name2:
    deletionPolicy: Rebuena
    customRole: "database_admin"

DatabaseInstances:
  db-name:
    externalName: my-db-external-name
    databaseVersion: POSTGRES_14
    deletionProtection: true
    region: europe-west1
    connectionSecret:
      name: my-db-connection
      namespace: ""
    settings:
      - tier: db-f1-micro
        #diskSize: 20
        diskType: PD_SSD
        diskAutoresize: true
        activationPolicy: ALWAYS
        availabilityType: ZONAL
        #deletionProtectionEnabled: true
        databaseFlags: [ ]
        insightsConfig:
          - queryInsightsEnabled: false
        locationPreference:
          - zone: europe-west1-b
        ipConfiguration:
          - privateNetwork: projects/project-name/global/networks/network-name
            ipv4Enabled: false
        maintenanceWindow:
          - updateTrack: stable
            day: 2
            hour: 11
        backupConfiguration:
          - enabled: true
            location: eu
            pointInTimeRecoveryEnabled: true
            transactionLogRetentionDays: 7
            backupRetentionSettings:
              - retainedBackups: 7
        userLabels:
          site: global
          service: my-service

DatabaseUsers:
  postgres:
    databaseInstance: db-name
    passwordSecretRef:
      key: postgres-password
      name: postgresql
      namespace: my-namespace
