#gcpProject:
#providerConfigRef:

ProjectIAMMember:
  create: false
  role: "" # "roles/secretmanager.secretAccessor"

ServiceAccount:
  create: false
  deletionPolicy: Delete
  # description: "Default Service Account description"

ServiceAccountKey:
  create: false
  deletionPolicy: Delete

