nameOverride: "my-example"
fullnameOverride: "my-example-fullname"

gcpProject: my-google-project
providerConfigRef: gcp-my-google-project

ProjectIAMMember:
  create: true
  role: "roles/secretmanager.secretAccessor"

ServiceAccount:
  create: true
  deletionPolicy: Delete
  description: "My Service Account Description!"

ServiceAccountKey:
  create: true
  deletionPolicy: Delete

