#nameOverride: "my-example"
fullnameOverride: "myfullname"

annotations:
  common/first: "true"
  common/second: "true"

gcpProject: my-google-project
providerConfigRef: gcp-my-google-project

GlobalAddress:
  externalAddress:
    description: Just an example
    address: 127.0.0.1
    addressType: EXTERNAL

ManagedSSLCertificate:
  my-external-name:
    domains:
    - test.example.com.

ComputeAddress:
  externalAddress:
    description: Just an example
    address: 127.0.0.1
    addressType: EXTERNAL
    region: us-west1

ServiceAccounts:
  name1:
    deletionPolicy: Delete
    description: "My Service Account 1 Description!"
  name2:
    deletionPolicy: Rebuena
    description: "My Service Account 2 Description!"

ServiceAccountKeys:
  name1:
    deletionPolicy: Delete
  name2:
    deletionPolicy: Rebuena
    useServiceAccountId: true

ProjectIAMCustomRoles:
  database-admin:
    project: ""
    externalName: database_admin
    title: Database Admin
    description: Custom role for administrate databases
    providerConfigRef: provider-ref
    permissions:
    - cloudsql.databases.create
    - cloudsql.databases.delete
    - cloudsql.databases.update
    - cloudsql.instances.create
    - cloudsql.instances.delete
    - cloudsql.instances.update
    - cloudsql.users.create
    - cloudsql.users.delete
    - cloudsql.users.update

ProjectIAMMembers:
  name1:
    annotations:
      specific: "true"
    deletionPolicy: Delete
    role: "roles/secretmanager.secretAccessor"
  name2:
    deletionPolicy: Rebuena
    customRole: "database_admin"
    type: group
    email: core@softonic.com

DatabaseInstances:
  db-name:
    externalName: my-db-external-name
    databaseVersion: POSTGRES_14
    deletionProtection: true
    region: europe-west1
    connectionSecret:
      name: my-db-connection
      namespace: ""
    settings:
      - tier: db-f1-micro
        #diskSize: 20
        diskType: PD_SSD
        diskAutoresize: true
        activationPolicy: ALWAYS
        availabilityType: ZONAL
        #deletionProtectionEnabled: true
        databaseFlags: []
        insightsConfig:
          - queryInsightsEnabled: false
        locationPreference:
          - zone: europe-west1-b
        ipConfiguration:
          - privateNetwork: projects/project-name/global/networks/network-name
            ipv4Enabled: false
        maintenanceWindow:
          - updateTrack: stable
            day: 2
            hour: 11
        backupConfiguration:
          - enabled: true
            location: eu
            pointInTimeRecoveryEnabled: true
            transactionLogRetentionDays: 7
            backupRetentionSettings:
              - retainedBackups: 7
        userLabels:
          site: global
          service: my-service

DatabaseUsers:
  postgres:
    databaseInstance: db-name
    passwordSecretRef:
      key: postgres-password
      name: postgresql
      namespace: my-namespace

CertificateMaps:
  softonic-ru:
    externalName: softonic-ru
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    labels:
      softonic.io/certificateMap: softonic-ru
CertificateMapEntries:
  softonic-ru:
    externalName: softonic-ru
    hostname: "softonic.ru"
    deletionPolicy: Orphan
    description: "certificate map entry for softonic.ru"
    certificate: "softonic-ru"
    matchLabels:
      softonic.io/certificateMap: softonic-ru
  wildcard-softonic-ru:
    externalName: wildcard-softonic-ru
    hostname: "*.softonic.ru"
    deletionPolicy: Orphan
    description: "certificate map entry wildcard for softonic.ru"
    certificate: "softonic-ru"
    matchLabels:
      softonic.io/certificateMap: softonic-ru
Certificates:
  softonic-ru:
    externalName: softonic-ru
    gcpProjectId: 956089745671
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    domains:
    - '*.softonic.ru'
    - 'softonic.ru'
    scope: "DEFAULT"
    dnsAuthorization: 'softonic-ru'
dnsAuthorizations:
  softonic-ru:
    externalName: softonic-ru
    deletionPolicy: Orphan
    description: "certificate manager for softonic.ru"
    domain: softonic.ru
SSLCertificates:
  filehippo-com:
    certificateKey: filehippo.crt
    certificateName: filehippo-crt
    privateKey: filehippo.key
    privateName: filehippo-key
    namespace: filehippo
