{{- range $key, $value := $.Values.BackendService -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
    healthChecksSelector:
      matchLabels:
        softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $value.healthChecksSelector }}
    loadBalancingScheme: {{ $value.loadBalancingScheme }}
  {{- with $value.backend }}
    backend:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with $value.securityPolicy }}
    securityPolicy: {{ $value.securityPolicy }}
  {{- end }}
  {{- with $value.logConfig }}
    logConfig:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
{{ end -}}
