{{- range $key, $value := $.Values.BucketIAMMembers -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  name: {{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    bucket: "{{ $value.bucket }}"
    member: "{{ $value.member }}"
    role: "{{ $value.role }}"
  providerConfigRef:
    name: {{ $value.providerConfigRef }}
{{ end -}}
