{{- range $key, $value := $.Values.Buckets -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}

spec:
  forProvider:
    location: {{ $value.location }}
    storageClass: {{ $value.storageClass }}
    project: {{ $.Values.gcpProject }}

  providerConfigRef:
    name: {{ $value.providerConfigRef }}
{{ end -}}
