{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $accountName, $value := $providerConfigRef.Buckets }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
{{- if $value.enabled }}
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ $accountName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    crossplane.io/external-name: {{ $value.externalName | default $accountName | quote }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  forProvider:
    location: {{ $value.location }}
    storageClass: {{ $value.storageClass }}
    project: {{ $projectName }}

  providerConfigRef:
    name: {{ $value.providerConfigRef }}
{{ end -}}
{{ end -}}
{{ end -}}
{{ end -}}
