{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $aclName, $value := $providerConfigRef.BucketAccessControl }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
{{- if $value.enabled }}
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketAccessControl
metadata:
  name: {{ $aclName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $aclName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  deletionPolicy: Orphan
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
    bucket: "{{ $value.bucket }}"
    entity: "{{ $value.entity }}"
    role: "{{ $value.role }}"
  providerConfigRef:
    name: {{ $value.providerConfigRef }}
{{ end -}}
{{ end -}}
{{ end -}}
{{ end -}}
