{{- range $key, $value := $.Values.CertificateMaps -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
{{- $mergedLabels := mergeOverwrite dict $.Values.labels (default dict $value.labels) }}
---
apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: CertificateMap
metadata:
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $mergedLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  deletionPolicy: Orphan
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
    description: {{ $value.description }}
    project: {{ $.Values.gcpProject }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
{{ end -}}
