{{- range $key, $value := $.Values.CertificateMapEntries -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: CertificateMapEntry
metadata:
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
spec:
  forProvider:
    certificates:
      # projects/official-provider-testing/locations/global/certificates/certificate
      - projects/{{ $.Values.gcpProject }}/locations/global/certificates/{{ $value.certificate }}
    description: My acceptance test certificate map entry
    labels:
      acc-test: "true"
      terraform: "true"
    mapSelector:
      matchLabels:
        {{- with $value.matchLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    matcher: PRIMARY
{{ end -}}
