{{- range $key, $value := $.Values.DatabaseInstances -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
  forProvider:
    databaseVersion: {{ $value.databaseVersion }}
    deletionProtection: {{ $value.deletionProtection }}
    region: {{ $value.region }}
  {{- with $value.settings }}
    settings:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  writeConnectionSecretToRef:
    name: {{ $value.connectionSecret.name }}
    namespace: {{ default $.Release.Namespace $value.connectionSecret.namespace }}
{{ end -}}