{{- range $key, $value := $.Values.DatabaseUsers -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
  forProvider:
    {{- with $value.host }}
    host: {{ . | quote }}
    {{- end }}
    instanceRef:
      name: {{ $value.databaseInstance }}
    {{- with $value.passwordSecretRef }}
    passwordSecretRef:
      namespace: {{ $.Release.Namespace }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with $value.userSecret }}
  writeConnectionSecretToRef:
    name: {{ .name }}
    namespace: {{ default $.Release.Namespace .namespace }}
  {{- end }}
{{ end -}}
