{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $resourceName, $value := $providerConfigRef.NodePools }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  name: {{ $resourceName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $resourceName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  deletionPolicy: Orphan
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
    cluster: "{{ $value.cluster }}"
    location: "{{ $value.location }}"
    project: "{{ $projectName }}"
    nodeConfig:
    {{- with $value.nodeConfig }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    management:
    {{- with $value.management }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if $value.upgradeSettings }}
    upgradeSettings:
    {{- with $value.upgradeSettings }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- if not $value.autoscaling }}
    nodeCount: {{ $value.nodeCount }}
{{- end }}
  initProvider:
{{- if $value.autoscaling }}
    autoscaling:
    {{- with $value.autoscaling }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
  providerConfigRef:
    name: {{ $providerConfigRefName }}
{{- end }}
{{- end }}
{{- end }}
