{{- range $key, $value := $.Values.ProjectIAMMembers -}}
{{- $valueWithProject := dict "gcpProject" $.Values.gcpProject "value" $value }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
#    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
{{- if eq $value.type "group" }}
    member: "group:{{ $value.email }}"
{{- else }}
    member: "serviceAccount:{{ include "crossplane.fullname" $ }}--{{ $key }}@{{ required "Required GCP Project value" $.Values.gcpProject }}.iam.gserviceaccount.com"
{{- end }}
    role: {{ include "crossplane.role" $valueWithProject }}
    project: {{ required "Required GCP Project value" $.Values.gcpProject }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $.Values.providerConfigRef }}
{{ end -}}
