{{- range $key, $value := $.Values.ProjectIAMMembers -}}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    member: "serviceAccount:{{ include "crossplane.fullname" $ }}--{{ $key }}@{{ required "Required GCP Project value" $.Values.gcpProject }}.iam.gserviceaccount.com"
    role: "{{ required "Required role value $value.role" $value.role }}"
    project: {{ required "Required GCP Project value" $.Values.gcpProject }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $.Values.providerConfigRef }}
{{ end -}}
