{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $accountName, $value := $providerConfigRef.ProjectIAMCustomRoles }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMCustomRole
metadata:
  name: {{ $accountName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $accountName | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  deletionPolicy: Orphan
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
    title: {{ $value.title }}
    description: {{ $value.description }}
    project: {{ $projectName }}
    {{- with $value.permissions }}
    permissions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  providerConfigRef:
    name: {{ $providerConfigRefName }}
{{ end -}}
{{ end -}}
{{ end -}}
