{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $accountName, $value := $providerConfigRef.ProjectIAMMembers }}
{{- $valueWithProject := dict "gcpProject" $projectName "value" $value }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not $value.deletionPolicy) (not $value.managementPolicies) }}
  managementPolicies:
    - Create
    - Update
    - Observe
  {{- end }}
  forProvider:
{{- if $value.member }}
    member: {{ $value.member }}
{{- else if eq $value.type "group" }}
    member: "group:{{ $value.email }}"
{{- else }}
    member: "serviceAccount:{{ include "crossplane.fullname" $ }}--{{ $accountName }}@{{ required "Required GCP Project value" $projectName }}.iam.gserviceaccount.com"
{{- end }}
    role: {{ include "crossplane.role" $valueWithProject }}
    project: {{ required "Required GCP Project value" $projectName }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $providerConfigRefName }}
{{ end -}}
{{ end -}}
{{ end -}}
