{{- range $key, $value := $.Values.ProjectIAMMembers -}}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ $key }}
  labels:
    softonic.io/crossplane: {{ $key }}-project-iam-member
spec:
  forProvider:
    member: "serviceAccount:{{ $key }}@{{ required "Required GCP Project value" $.Values.gcpProject }}.iam.gserviceaccount.com"
    role: "{{ required "Required role value $value.role" $value.role }}"
    project: {{ required "Required GCP Project value" $.Values.gcpProject }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $.Values.providerConfigRef }}
{{ end -}}
