{{- range $key, $value := $.Values.ServiceAccountKeys -}}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: {{ $key }}
  labels:
    softonic.io/crossplane: {{ $key }}-service-account-key
spec:
  forProvider:
    serviceAccountIdSelector:
      matchLabels:
        softonic.io/crossplane: {{ $key }}-service-account
  deletionPolicy: {{ $value.deletionPolicy }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $.Values.providerConfigRef }}
  writeConnectionSecretToRef:
    name: {{ $.Release.Name }}-key
    namespace: {{ $.Release.Namespace }}
{{ end -}}
