{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $accountName, $value := $providerConfigRef.ServiceAccountKeys }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    {{- if $value.useServiceAccountId }}
    serviceAccountId: {{ include "crossplane.fullname" $ }}--{{ $accountName }}@{{ $.Values.gcpProject }}.iam.gserviceaccount.com
    {{- else }}
    serviceAccountIdSelector:
      matchLabels:
        softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
    {{- end }}
  {{- if $value.deletionPolicy }}
  deletionPolicy: {{ $value.deletionPolicy }}
  {{- end }}
  {{- with $value.managementPolicies }}
  managementPolicies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $providerConfigRefName }}
  writeConnectionSecretToRef:
    name: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
    namespace: {{ $.Release.Namespace }}
{{ end -}}
{{ end -}}
{{ end -}}
