{{- if .Values.ServiceAccountKey.create -}}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: {{ include "crossplane.fullname" . }}
  labels:
    {{- include "crossplane.labels" . | nindent 4 }}
spec:
  forProvider:
    serviceAccountIdSelector:
      matchLabels:
        softonic.io/crossplane: {{ include "crossplane.name" . }}-service-account
  deletionPolicy: {{ .Values.ServiceAccountKey.deletionPolicy }}
  providerConfigRef:
    name: {{ required "A valid .Values.providerConfigRef entry required" .Values.providerConfigRef }}
  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-key
    namespace: {{ .Release.Namespace }}
{{- end }}
