{{- range $key, $value := $.Values.ServiceAccountKeys -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
#    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    {{- if $value.useServiceAccountId }}
    serviceAccountId: {{ include "crossplane.fullname" $ }}--{{ $key }}@{{ $.Values.gcpProject }}.iam.gserviceaccount.com
    {{- else }}
    serviceAccountIdSelector:
      matchLabels:
        softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
    {{- end }}
  deletionPolicy: {{ $value.deletionPolicy }}
  providerConfigRef:
    name: {{ required "A valid $.Values.providerConfigRef entry required" $.Values.providerConfigRef }}
  writeConnectionSecretToRef:
    name: {{ include "crossplane.fullname" $ }}--{{ $key }}
    namespace: {{ $.Release.Namespace }}
{{ end -}}
