{{- range $projectName, $project := .Values.projects }}
{{- range $providerConfigRefName, $providerConfigRef := $project }}
{{- range $accountName, $value := $providerConfigRef.ServiceAccounts }}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  deletionPolicy: {{ required "Requires the deletionPolicy value to be Delete or Orphan" $value.deletionPolicy }}
  forProvider:
    description: {{ required "A valid $key.description entry required" $value.description }}
    displayName: {{ include "crossplane.fullname" $ }}--{{ $accountName }}
    project: {{ $projectName }}
  providerConfigRef:
    name: {{ $providerConfigRefName }}
{{- end }}
{{- end }}
{{- end }}
