{{- if .Values.ServiceAccount.create -}}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane.fullname" . }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.name" . }}-service-account
    {{- include "crossplane.labels" . | nindent 4 }}
spec:
  deletionPolicy: {{ .Values.ServiceAccount.deletionPolicy }}
  forProvider:
    description: {{ required "A valid .Values.ServiceAccount.description entry required" .Values.ServiceAccount.description }}
    displayName: {{ include "crossplane.fullname" . }}
    project: {{ required "Required GCP Project value" .Values.gcpProject }}
  providerConfigRef:
    name: {{ required "A valid .Values.providerConfigRef entry required" .Values.providerConfigRef }}
{{- end }}
