{{- range $key, $value := $.Values.ServiceAccounts -}}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}-service-account
spec:
  deletionPolicy: {{ $value.deletionPolicy }}
  forProvider:
    description: {{ required "A valid $key.description entry required" $value.description }}
    displayName: {{ include "crossplane.fullname" $ }}--{{ $key }}
    project: {{ $.Values.gcpProject }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
{{ end -}}
