{{- range $key, $value := $.Values.URLMap -}}
{{- $mergedAnnotations := mergeOverwrite dict $.Values.annotations (default dict $value.annotations) }}
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: URLMap
metadata:
  name: {{ include "crossplane.fullname" $ }}--{{ $key }}
  labels:
    softonic.io/crossplane: {{ include "crossplane.fullname" $ }}--{{ $key }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    crossplane.io/external-name: {{ $value.externalName | default $key | quote }}
  {{- with $mergedAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    defaultService: {{ $value.defaultService }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef }}
{{ end -}}
